- name: Config NFS for app files
  hosts: nfs
  become: true
  vars_files:
    - 'vars/vars.yaml'
  tasks:

   # - name: Install common
   #   ansible.builtin.import_role:
   #     name: common-config-docker

    # --- Config firewalld
    - name: Install common
      ansible.builtin.import_role:
        name: base

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Move eth1 to internal zone
      ansible.builtin.shell: "firewall-cmd --zone=internal --change-interface=eth1 --permanent"

    - name: Enable nfs services
      ansible.posix.firewalld:
        zone: internal
        service: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - nfs
        - rpc-bind
        - mountd

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    # ---

    - name: Install nfs packages
      ansible.builtin.yum:
        name:
          - nfs-utils
        state: present

    - name: Start nfs service
      ansible.builtin.service:
        name: nfs-server
        state: started
        enabled: true

    - name: Create share data directory
      ansible.builtin.file:
        path: "{{ nfs_data_dir }}"
        state: directory
        owner: nobody
        group: nobody
        recurse: yes
        mode: '0777'

    - name: copy exports
      ansible.builtin.template:
        src: exports.j2
        dest: /etc/exports

    - name: export filesystem
      ansible.builtin.shell: exportfs -arv

#- name: Run exporters
#  hosts: nfs
#  become: true
 # tasks:
#    - name: Install edge duckprom node
 #     ansible.builtin.import_role:
 #       name: nmix.duckprom
 #     vars:
 #       duckprom_dir: /opt/duckprom
  #      duckprom_grafana_host: 10.10.1.143
 #       duckprom_basic_auth_enabled: false